-- Hold top level zone file
RECREATE TABLE zone_files
(
    id int GENERATED BY DEFAULT AS identity PRIMARY KEY,
    origin varchar(255) NOT NULL,
    soa int NOT NULL
);

-- Hold domains
RECREATE TABLE domains
(
    id int GENERATED BY DEFAULT AS identity PRIMARY KEY,
    zone_file_id int NOT NULL,
    domain_name varchar(255) NOT NULL UNIQUE,
    status varchar(255) NOT NULL,
    FOREIGN KEY (zone_file_id) REFERENCES zone_files(id) ON DELETE CASCADE
);

-- Holds nameservers seen, references to domain (special handling for NS records)
RECREATE TABLE nameservers
(
    id int GENERATED BY DEFAULT AS identity PRIMARY KEY,
    zone_file_id int NOT NULL,
    nameserver varchar(255) NOT NULL UNIQUE,
    domain_count int NOT NULL, 
    FOREIGN KEY (zone_file_id) REFERENCES zone_files(id) ON DELETE CASCADE
);

-- Link table between domains and nameservers
RECREATE TABLE domain_nameservers
(
    id int GENERATED BY DEFAULT AS identity PRIMARY KEY,
    domain_id int NOT NULL,
    nameserver_id int NOT NULL,
    FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE CASCADE,
    FOREIGN KEY (nameserver_id) REFERENCES nameservers(id) ON DELETE CASCADE,
    UNIQUE(domain_id, nameserver_id)
);

-- Holds domain rrdata
RECREATE TABLE domain_rdata
(
    id int GENERATED BY DEFAULT AS identity PRIMARY KEY,
    domain_id int NOT NULL,
    rrtype varchar(10) NOT NULL, -- 10 might be too long here but whatever
    rdata blob SUB_TYPE text NOT NULL,
    FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE CASCADE
);

-- Hold reverse zone information
RECREATE TABLE ptr_records
(
    id int GENERATED BY DEFAULT AS identity PRIMARY KEY,
    zone_file_id int NOT NULL,
    ip_address varchar(39) NOT NULL,
    reverse_lookup_name varchar(255) NOT NULL,
    FOREIGN KEY (zone_file_id) REFERENCES zone_files(id) ON DELETE CASCADE,
    UNIQUE (ip_address, reverse_lookup_name)
);

-- Domain/PTR link table
RECREATE TABLE domain_ptr_records
(
    id int GENERATED BY DEFAULT AS identity PRIMARY KEY,
    domain_id int NOT NULL,
    ptr_record_id int NOT NULL,
    FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE CASCADE,
    FOREIGN KEY (ptr_record_id) REFERENCES ptr_records(id) ON DELETE CASCADE,
    UNIQUE(domain_id, ptr_record_id)
)